flags: {}
packages:
- '.'
- location:
    git: https://github.com/Teaspot-Studio/inline-c.git
    commit: 3b57bf189dbe7efedaac42e7ac705adea5bd7f6c
- location:
    git: https://github.com/Teaspot-Studio/inline-c-cpp.git
    commit: 68ec7290766c4f7997361d4e74e6ad4c15dd26b6
extra-deps: []
resolver: lts-6.9

extra-lib-dirs:
- /usr/lib64/Urho3D
extra-include-dirs:
- /usr/include
- /usr/include/Urho3D/ThirdParty