flags: {}
packages:
- '.'
- location:
    git: git@github.com:fpco/inline-c.git
    commit: deaf28b0b6641a44908fb940a122da6c26b243fb
- location:
    git: git@github.com:fpco/inline-c-cpp.git
    commit: 12319586f19f08f6b32984e2a1f15c76db290e0c
extra-deps: []
resolver: nightly-2015-07-30
