flags: {}
packages:
- '.'
- 'urho3d-bindgen'
- location:
    git: https://github.com/Teaspot-Studio/inline-c.git
    commit: 29fdcec7292bc1fe0859548de42608a5a243df10
  extra-dep: true
- location:
    git: https://github.com/Teaspot-Studio/inline-c-cpp.git
    commit: 68ec7290766c4f7997361d4e74e6ad4c15dd26b6
  extra-dep: true
extra-deps: []
resolver: lts-10.7

extra-lib-dirs:
- /usr/lib64/Urho3D
extra-include-dirs:
- /usr/include
- /usr/include/Urho3D/ThirdParty
