flags: {}
packages:
- '.'
- location:
    git: git@github.com:Teaspot-Studio/inline-c.git
    commit: 1541964fa9d31ce9e474b39b9f0ad3b842362093
- location:
    git: git@github.com:fpco/inline-c-cpp.git
    commit: 12319586f19f08f6b32984e2a1f15c76db290e0c
extra-deps: []
resolver: lts-5.10

extra-lib-dirs:
- /usr/lib64/Urho3D
extra-include-dirs:
- /usr/include
- /usr/include/Urho3D/ThirdParty